spring.application.name=blackjack
server.port=8080
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=blackjack
spring.data.mongodb.auto-index-creation=true
spring.r2dbc.url=r2dbc:mariadb://localhost:3306/blackjack
spring.r2dbc.username=devs
spring.r2dbc.password=pw1234
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

